### ISSUE TITLE
Cannot `go get`

### ISSUE THREAD

**Issue by mattrco** [takluyver/igo#1]
```
$ go get github.com/takluyver/igo
# pkg-config --cflags libzmq libzmq libzmq libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
exit status 1
```

Figuring this was because I was missing the libzmq development package, I ran `sudo apt-get install libzmq-dev` (I'm running Ubuntu 12.04). But then:

```
go get github.com/takluyver/igo
# github.com/alecthomas/gozmq
37: error: 'ZMQ_RCVTIMEO' undeclared (first use in this function)
37: error: 'ZMQ_SNDTIMEO' undeclared (first use in this function)
```

One of the deps looks broken. Go version is 1.2.

Happy to look into this further and fix the dep and at a working revision if this isn't something you've seen before.

**Comment by aterrel** [comment]
https://github.com/alecthomas/gozmq has been deprecated and suggests https://github.com/pebbe/zmq4

**Comment by takluyver** [comment]
PRs to update it welcome. I'm not really interested in working on this at the moment - the go eval tools were too limited for it to be useful.

**Comment by aterrel** [comment]
@takluyver thanks for the response! It might be reasonable to put that in the readme, would have saved me time going down some rabbit holes to get this to work.
